# Generated by Django 5.0.1 on 2024-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_group_contacts_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_contacts',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
