# Generated by Django 5.0.1 on 2024-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_group_contacts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_contacts',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
