# Generated by Django 5.0.1 on 2024-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='response_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], max_length=50),
        ),
    ]
